// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth_sessions.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const conditionalRotateAuthSessionRefreshToken = `-- name: ConditionalRotateAuthSessionRefreshToken :execresult
UPDATE auth_sessions
SET refresh_token_hash = ?,
    refresh_expires_at = ?,
    last_refreshed_at = ?,
    last_seen_at = ?,
    version = version + 1,
    updated_at = CURRENT_TIMESTAMP
WHERE session_id = ?
  AND refresh_token_hash = ?
  AND version = ?
  AND status = 'ACTIVE'
  AND refresh_expires_at > ?
`

type ConditionalRotateAuthSessionRefreshTokenParams struct {
	RefreshTokenHash   string
	RefreshExpiresAt   time.Time
	LastRefreshedAt    sql.NullTime
	LastSeenAt         sql.NullTime
	SessionID          string
	RefreshTokenHash_2 string
	Version            int32
	RefreshExpiresAt_2 time.Time
}

func (q *Queries) ConditionalRotateAuthSessionRefreshToken(ctx context.Context, arg ConditionalRotateAuthSessionRefreshTokenParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, conditionalRotateAuthSessionRefreshToken,
		arg.RefreshTokenHash,
		arg.RefreshExpiresAt,
		arg.LastRefreshedAt,
		arg.LastSeenAt,
		arg.SessionID,
		arg.RefreshTokenHash_2,
		arg.Version,
		arg.RefreshExpiresAt_2,
	)
}

const createAuthSession = `-- name: CreateAuthSession :execresult
INSERT INTO auth_sessions (
    session_id,
    user_id,
    refresh_token_hash,
    status,
    issued_at,
    refresh_expires_at,
    last_refreshed_at,
    last_seen_at,
    revoked_at,
    revoke_reason,
    client_ip_hash,
    user_agent_hash,
    user_agent_summary,
    version
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAuthSessionParams struct {
	SessionID        string
	UserID           int64
	RefreshTokenHash string
	Status           string
	IssuedAt         time.Time
	RefreshExpiresAt time.Time
	LastRefreshedAt  sql.NullTime
	LastSeenAt       sql.NullTime
	RevokedAt        sql.NullTime
	RevokeReason     sql.NullString
	ClientIpHash     sql.NullString
	UserAgentHash    sql.NullString
	UserAgentSummary sql.NullString
	Version          int32
}

func (q *Queries) CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createAuthSession,
		arg.SessionID,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.Status,
		arg.IssuedAt,
		arg.RefreshExpiresAt,
		arg.LastRefreshedAt,
		arg.LastSeenAt,
		arg.RevokedAt,
		arg.RevokeReason,
		arg.ClientIpHash,
		arg.UserAgentHash,
		arg.UserAgentSummary,
		arg.Version,
	)
}

const findAuthSessionByRefreshTokenHash = `-- name: FindAuthSessionByRefreshTokenHash :one
SELECT id, session_id, user_id, refresh_token_hash, status, issued_at, refresh_expires_at,
       last_refreshed_at, last_seen_at, revoked_at, revoke_reason, client_ip_hash,
       user_agent_hash, user_agent_summary, version, created_at, updated_at
FROM auth_sessions
WHERE refresh_token_hash = ?
`

func (q *Queries) FindAuthSessionByRefreshTokenHash(ctx context.Context, refreshTokenHash string) (AuthSession, error) {
	row := q.db.QueryRowContext(ctx, findAuthSessionByRefreshTokenHash, refreshTokenHash)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.Status,
		&i.IssuedAt,
		&i.RefreshExpiresAt,
		&i.LastRefreshedAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.ClientIpHash,
		&i.UserAgentHash,
		&i.UserAgentSummary,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findAuthSessionBySessionID = `-- name: FindAuthSessionBySessionID :one
SELECT id, session_id, user_id, refresh_token_hash, status, issued_at, refresh_expires_at,
       last_refreshed_at, last_seen_at, revoked_at, revoke_reason, client_ip_hash,
       user_agent_hash, user_agent_summary, version, created_at, updated_at
FROM auth_sessions
WHERE session_id = ?
`

func (q *Queries) FindAuthSessionBySessionID(ctx context.Context, sessionID string) (AuthSession, error) {
	row := q.db.QueryRowContext(ctx, findAuthSessionBySessionID, sessionID)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.Status,
		&i.IssuedAt,
		&i.RefreshExpiresAt,
		&i.LastRefreshedAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.ClientIpHash,
		&i.UserAgentHash,
		&i.UserAgentSummary,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeAuthSessionBySessionID = `-- name: RevokeAuthSessionBySessionID :execresult
UPDATE auth_sessions
SET status = 'REVOKED',
    revoked_at = ?,
    revoke_reason = ?,
    version = version + 1,
    updated_at = CURRENT_TIMESTAMP
WHERE session_id = ?
  AND status = 'ACTIVE'
`

type RevokeAuthSessionBySessionIDParams struct {
	RevokedAt    sql.NullTime
	RevokeReason sql.NullString
	SessionID    string
}

func (q *Queries) RevokeAuthSessionBySessionID(ctx context.Context, arg RevokeAuthSessionBySessionIDParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, revokeAuthSessionBySessionID, arg.RevokedAt, arg.RevokeReason, arg.SessionID)
}

const updateAuthSessionLastSeenAt = `-- name: UpdateAuthSessionLastSeenAt :execresult
UPDATE auth_sessions
SET last_seen_at = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE session_id = ?
  AND status = 'ACTIVE'
`

type UpdateAuthSessionLastSeenAtParams struct {
	LastSeenAt sql.NullTime
	SessionID  string
}

func (q *Queries) UpdateAuthSessionLastSeenAt(ctx context.Context, arg UpdateAuthSessionLastSeenAtParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateAuthSessionLastSeenAt, arg.LastSeenAt, arg.SessionID)
}

const updateAuthSessionStatus = `-- name: UpdateAuthSessionStatus :execresult
UPDATE auth_sessions
SET status = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE session_id = ?
`

type UpdateAuthSessionStatusParams struct {
	Status    string
	SessionID string
}

func (q *Queries) UpdateAuthSessionStatus(ctx context.Context, arg UpdateAuthSessionStatusParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateAuthSessionStatus, arg.Status, arg.SessionID)
}
