// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"
)

type AuthSession struct {
	ID               int64
	SessionID        string
	UserID           int64
	RefreshTokenHash string
	Status           string
	IssuedAt         time.Time
	RefreshExpiresAt time.Time
	LastRefreshedAt  sql.NullTime
	LastSeenAt       sql.NullTime
	RevokedAt        sql.NullTime
	RevokeReason     sql.NullString
	ClientIpHash     sql.NullString
	UserAgentHash    sql.NullString
	UserAgentSummary sql.NullString
	Version          int32
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type Role struct {
	ID          int64
	Code        string
	Name        string
	Description sql.NullString
	CreatedAt   time.Time
}

type SystemBootstrapRecord struct {
	ID          int64
	Environment string
	Note        string
	CreatedAt   time.Time
}

type User struct {
	ID           int64
	Username     string
	Email        string
	PasswordHash string
	Status       string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type UserRole struct {
	ID        int64
	UserID    int64
	RoleID    int64
	CreatedAt time.Time
}
