// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: roles.sql

package sqlc

import (
	"context"
	"database/sql"
	"strings"
)

const addRoleToUser = `-- name: AddRoleToUser :execresult
INSERT INTO user_roles (user_id, role_id)
VALUES (?, ?)
`

type AddRoleToUserParams struct {
	UserID int64
	RoleID int64
}

func (q *Queries) AddRoleToUser(ctx context.Context, arg AddRoleToUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addRoleToUser, arg.UserID, arg.RoleID)
}

const findRoleByCode = `-- name: FindRoleByCode :one
SELECT id, code, name, description, created_at
FROM roles
WHERE code = ?
`

func (q *Queries) FindRoleByCode(ctx context.Context, code string) (Role, error) {
	row := q.db.QueryRowContext(ctx, findRoleByCode, code)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const findRoleCodesByUserID = `-- name: FindRoleCodesByUserID :many
SELECT r.code
FROM roles r
JOIN user_roles ur ON ur.role_id = r.id
WHERE ur.user_id = ?
ORDER BY r.code ASC
`

func (q *Queries) FindRoleCodesByUserID(ctx context.Context, userID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, findRoleCodesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var code string
		if err := rows.Scan(&code); err != nil {
			return nil, err
		}
		items = append(items, code)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findRoleCodesByUserIDs = `-- name: FindRoleCodesByUserIDs :many
SELECT ur.user_id,
       r.code AS role_code
FROM user_roles ur
JOIN roles r ON r.id = ur.role_id
WHERE ur.user_id IN (/*SLICE:user_ids*/?)
ORDER BY ur.user_id ASC, r.code ASC
`

type FindRoleCodesByUserIDsRow struct {
	UserID   int64
	RoleCode string
}

func (q *Queries) FindRoleCodesByUserIDs(ctx context.Context, userIds []int64) ([]FindRoleCodesByUserIDsRow, error) {
	query := findRoleCodesByUserIDs
	var queryParams []interface{}
	if len(userIds) > 0 {
		for _, v := range userIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:user_ids*/?", strings.Repeat(",?", len(userIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:user_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindRoleCodesByUserIDsRow
	for rows.Next() {
		var i FindRoleCodesByUserIDsRow
		if err := rows.Scan(&i.UserID, &i.RoleCode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
