// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countUsersByCriteria = `-- name: CountUsersByCriteria :one
SELECT COUNT(*)
FROM users
WHERE (? IS NULL OR username LIKE CONCAT('%', ?, '%'))
  AND (? IS NULL OR email LIKE CONCAT('%', ?, '%'))
  AND (? IS NULL OR status = ?)
  AND (? IS NULL OR created_at >= ?)
  AND (? IS NULL OR created_at <= ?)
  AND (? IS NULL OR updated_at >= ?)
  AND (? IS NULL OR updated_at <= ?)
`

type CountUsersByCriteriaParams struct {
	Username      interface{}
	Email         interface{}
	Status        sql.NullString
	CreatedAtFrom sql.NullTime
	CreatedAtTo   sql.NullTime
	UpdatedAtFrom sql.NullTime
	UpdatedAtTo   sql.NullTime
}

func (q *Queries) CountUsersByCriteria(ctx context.Context, arg CountUsersByCriteriaParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsersByCriteria,
		arg.Username,
		arg.Username,
		arg.Email,
		arg.Email,
		arg.Status,
		arg.Status,
		arg.CreatedAtFrom,
		arg.CreatedAtFrom,
		arg.CreatedAtTo,
		arg.CreatedAtTo,
		arg.UpdatedAtFrom,
		arg.UpdatedAtFrom,
		arg.UpdatedAtTo,
		arg.UpdatedAtTo,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersByEmail = `-- name: CountUsersByEmail :one
SELECT COUNT(*)
FROM users
WHERE email = ?
`

func (q *Queries) CountUsersByEmail(ctx context.Context, email string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsersByEmail, email)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersByUsername = `-- name: CountUsersByUsername :one
SELECT COUNT(*)
FROM users
WHERE username = ?
`

func (q *Queries) CountUsersByUsername(ctx context.Context, username string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsersByUsername, username)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :execresult
INSERT INTO users (username, email, password_hash, status)
VALUES (?, ?, ?, ?)
`

type CreateUserParams struct {
	Username     string
	Email        string
	PasswordHash string
	Status       string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Status,
	)
}

const findUserByID = `-- name: FindUserByID :one
SELECT id, username, email, password_hash, status, created_at, updated_at
FROM users
WHERE id = ?
`

func (q *Queries) FindUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, findUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserByUsernameOrEmail = `-- name: FindUserByUsernameOrEmail :one
SELECT id, username, email, password_hash, status, created_at, updated_at
FROM users
WHERE username = ?
   OR email = ?
LIMIT 1
`

type FindUserByUsernameOrEmailParams struct {
	Username string
	Email    string
}

func (q *Queries) FindUserByUsernameOrEmail(ctx context.Context, arg FindUserByUsernameOrEmailParams) (User, error) {
	row := q.db.QueryRowContext(ctx, findUserByUsernameOrEmail, arg.Username, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUsersPageByCriteria = `-- name: FindUsersPageByCriteria :many
SELECT id, username, email, password_hash, status, created_at, updated_at
FROM users
WHERE (? IS NULL OR username LIKE CONCAT('%', ?, '%'))
  AND (? IS NULL OR email LIKE CONCAT('%', ?, '%'))
  AND (? IS NULL OR status = ?)
  AND (? IS NULL OR created_at >= ?)
  AND (? IS NULL OR created_at <= ?)
  AND (? IS NULL OR updated_at >= ?)
  AND (? IS NULL OR updated_at <= ?)
ORDER BY created_at DESC, id DESC
LIMIT ? OFFSET ?
`

type FindUsersPageByCriteriaParams struct {
	Username      interface{}
	Email         interface{}
	Status        sql.NullString
	CreatedAtFrom sql.NullTime
	CreatedAtTo   sql.NullTime
	UpdatedAtFrom sql.NullTime
	UpdatedAtTo   sql.NullTime
	Limit         int32
	Offset        int32
}

func (q *Queries) FindUsersPageByCriteria(ctx context.Context, arg FindUsersPageByCriteriaParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, findUsersPageByCriteria,
		arg.Username,
		arg.Username,
		arg.Email,
		arg.Email,
		arg.Status,
		arg.Status,
		arg.CreatedAtFrom,
		arg.CreatedAtFrom,
		arg.CreatedAtTo,
		arg.CreatedAtTo,
		arg.UpdatedAtFrom,
		arg.UpdatedAtFrom,
		arg.UpdatedAtTo,
		arg.UpdatedAtTo,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserStatus = `-- name: UpdateUserStatus :execresult
UPDATE users
SET status = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateUserStatusParams struct {
	Status string
	ID     int64
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUserStatus, arg.Status, arg.ID)
}
